[package]
name = "tetris_bot_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "tetris_bot_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }